# Generated by Django 6.0 on 2025-12-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('event_type', models.CharField(choices=[('import_completed', 'Import Completed'), ('product_created', 'Product Created'), ('product_updated', 'Product Updated'), ('product_deleted', 'Product Deleted'), ('bulk_deleted', 'Bulk Deleted')], max_length=50)),
                ('enabled', models.BooleanField(default=True)),
                ('last_test_status', models.IntegerField(blank=True, null=True)),
                ('last_test_time_ms', models.IntegerField(blank=True, null=True)),
                ('last_test_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
