# Generated by Django 6.0 on 2025-12-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='importjob',
            old_name='error_message',
            new_name='error',
        ),
        migrations.RenameField(
            model_name='importjob',
            old_name='processed_rows',
            new_name='processed',
        ),
        migrations.RenameField(
            model_name='importjob',
            old_name='total_rows',
            new_name='total',
        ),
        migrations.RemoveField(
            model_name='importjob',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='importjob',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
