# Generated by Django 6.0 on 2025-12-20 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0002_rename_error_message_importjob_error_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='importjob',
            old_name='error',
            new_name='error_message',
        ),
        migrations.RenameField(
            model_name='importjob',
            old_name='processed',
            new_name='processed_rows',
        ),
        migrations.RenameField(
            model_name='importjob',
            old_name='total',
            new_name='total_rows',
        ),
    ]
