# Generated by Django 6.0 on 2025-12-19 18:44

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(django.db.models.functions.text.Lower('sku'), name='sku_lower_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('sku'), name='unique_sku_lower')],
            },
        ),
    ]
